web:
  name: marketpulse-bot
  runtime: python
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
  healthCheck: false
  regions:
    - was
  env:
    - key: TELEGRAM_BOT_TOKEN
      secret: TELEGRAM_BOT_TOKEN
    - key: TELEGRAM_CHAT_ID
      secret: TELEGRAM_CHAT_ID
    - key: GOOGLE_API_KEY
      secret: GOOGLE_API_KEY
